# Generated by Django 2.2.2 on 2019-06-07 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isavailable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
